// Constants describing the api routes
export const API_ROUTES = {
    SIGN_UP: '/clients/registerClient',
    SIGN_IN: '/clients/login',
    VERIFY_EMAIL: '/clients/emailVerification',
    RESEND_EMAIL: "/clients/resendEmail",
    GET_USER: "/clients/profile",
    GET_BENEFICIARY: "/beneficiaries",
    ASSET: "/assets",
    ACCOUNT: "/accounts",
    DOCUMENT: "/documents",
    CUSTOM_DETAILS: "/customDetails",
    FAMILY: "/familyDetails",
    NEXT_OF_KIN: "/next-of-kin",
    EXECUTOR: "/executor",
    CREATE_PLAN: '/plans',
    GET_PLANS: '/plans',
    GET_PLAN_PROJECTION: '/plans/projection',
    GET_ONE_PLAN: '/plans/:id',
    CREATE_TRANSACTION: '/transactions',
    GET_BANK_LIST: '/banks',
    GET_RATES: '/rates',
    GET_QUOTE: '/quotes',

};